language: python
python:
  - "3.6"
  - "3.7"

services:
  - docker

before_install:
  - docker pull franzinc/agraph:v7.0.0

install:
  - pip install -r requirements.txt

script:
  - pip freeze
  # generate new Brick ontology (in case this hasn't been run)
  - python generate_brick.py
  # -s flag: do not capture output (avoids killing test after 10 min)
  - pytest -s -vvvv
  # do integration tests
  - cd tests/integration && bash run_integration_tests.sh
