language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  # test the repo as-is
  # -s flag: do not capture output (avoids killing test after 10 min)
  - pytest -s
  # generate new Brick ontology (in case this hasn't been run)
  - python generate_brick.py
  # test again in case this broke anything
  - pytest -s
