name: Build

on:
  push:
    branches:
        - master
        - v1.*
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up AllegroGraph (Docker)
      run: |
        docker version
        docker pull franzinc/agraph:v7.1.0
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip freeze
    - name: Generate new Brick ontology
      # generate new Brick ontology (in case this hasn't been run)
      run: |
        make
        cat Brick.ttl
    - name: zip imports and extensions
      run: |
        zip -r imports.zip imports
        zip -r extensions.zip extensions
    - name: upload ttls
      if: ${{ matrix.python-version }} == "3.10"
      uses: actions/upload-artifact@v3
      with:
        name: Brick-ontology
        path: |
          Brick.ttl
          Brick+imports.ttl
          Brick+extensions.ttl
          Brick-only.ttl
          imports.zip
          extensions.zip
    - name: Run the tests
      # -s flag: do not capture output (avoids killing test after 10 min)
      run: |
        pytest -s -vvvv --durations=0 -n auto tests
