name: Build

on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6.12, 3.7.9, 3.8.5, 3.9.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up AllegroGraph (Docker)
      run: |
        docker version
        docker pull franzinc/agraph:v7.0.0
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip freeze
    - name: Generate new Brick ontology
      # generate new Brick ontology (in case this hasn't been run)
      run: |
        make
        cat Brick.ttl
    - name: Regenerate SHACL shapes
      run: |
        cd shacl
        python generate_shacl.py
        cd ..
    - name: Run the tests
      # -s flag: do not capture output (avoids killing test after 10 min)
      run: |
        pytest -s -vvvv
    - name: Do integration tests
      run: |
        cd tests/integration
        bash run_integration_tests.sh
